// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TS2210004.Models;

#nullable disable

namespace TS2210004.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240106064003_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TS2210004.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Role")
                        .HasColumnType("bit");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = "E01",
                            Age = 50,
                            EmployeeName = "Bill Gates",
                            Password = "123",
                            Role = true
                        },
                        new
                        {
                            EmployeeID = "E02",
                            Age = 25,
                            EmployeeName = "Ronaldo",
                            Password = "123",
                            Role = false
                        },
                        new
                        {
                            EmployeeID = "E04",
                            Age = 22,
                            EmployeeName = "Merida",
                            Password = "123",
                            Role = false
                        },
                        new
                        {
                            EmployeeID = "E08",
                            Age = 54,
                            EmployeeName = "John Vu",
                            Password = "123",
                            Role = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
