// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pretest.Data;

#nullable disable

namespace Pretest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240102104859_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pretest.Models.tblEmp", b =>
                {
                    b.Property<string>("EmpID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.HasKey("EmpID");

                    b.ToTable("tblEmps");

                    b.HasData(
                        new
                        {
                            EmpID = "E001",
                            FirstName = "nhan",
                            LastName = "tran",
                            Password = "123",
                            Salary = 12.34f
                        },
                        new
                        {
                            EmpID = "E002",
                            FirstName = "tien",
                            LastName = "nam",
                            Password = "123",
                            Salary = 56.78f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
